import { computeTiming } from '../pathOrder';

const DEFAULT_VIEWBOX = '0 0 646 226';
const DEFAULT_FILL = '#161311';
const DEFAULT_CANVAS_W = 600;
const DEFAULT_CANVAS_H = 300;

function parseViewBox(viewBox) {
  const parts = String(viewBox || '').trim().split(/\s+/).map(Number);
  if (parts.length === 4 && parts.every(Number.isFinite)) {
    return {
      minX: parts[0],
      minY: parts[1],
      width: Math.max(parts[2], 1),
      height: Math.max(parts[3], 1),
    };
  }
  return { minX: 0, minY: 0, width: 600, height: 200 };
}

export function generateExportSnippet({
  paths,
  isFill,
  viewBox,
  svgTransform,
  animStyle,
  animSpeed,
  clusterMeta,
  canvasWidth = DEFAULT_CANVAS_W,
  canvasHeight = DEFAULT_CANVAS_H,
}) {
  const speed = animSpeed || 1;
  const s = 1 / speed;
  const vb = isFill ? `0 0 ${canvasWidth} ${canvasHeight}` : (viewBox || DEFAULT_VIEWBOX);

  if (animStyle === 'flow') {
    const maxCluster = clusterMeta?.length
      ? Math.max(...clusterMeta.map((meta) => meta.clusterIndex))
      : 0;
    const totalDuration = ((maxCluster + 1) * 0.5 * s + 0.5 * s).toFixed(2);

    const pathsMarkup = paths.map((d) => `      <path d="${d}" fill-rule="evenodd"/>`).join('\n');
    const innerGroup = svgTransform && !isFill
      ? `    <g class="sig-paths" clip-path="url(#sig-reveal)">\n      <g transform="${svgTransform}" fill="${DEFAULT_FILL}" stroke="none">\n${pathsMarkup}\n      </g>\n    </g>`
      : `    <g class="sig-paths" clip-path="url(#sig-reveal)" fill="${DEFAULT_FILL}" stroke="none">\n${pathsMarkup}\n    </g>`;

    return `<!-- Signature Animation — generated by Signature Animator -->
<div style="max-width:500px;">
  <svg viewBox="${vb}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;overflow:hidden;">
    <style>
      @keyframes sigReveal {
        from { transform: translateX(-100%); }
        to { transform: translateX(0); }
      }
      .sig-reveal-rect { animation: sigReveal ${totalDuration}s cubic-bezier(0.25,0.1,0.25,1) forwards; }
    </style>
    <defs>
      <clipPath id="sig-reveal">
        <rect x="0" y="0" width="100%" height="100%" class="sig-reveal-rect" style="transform:translateX(-100%);"/>
      </clipPath>
    </defs>
${innerGroup}
  </svg>
</div>`;
  }

  const pathLines = paths.map((d, index) => {
    const meta = clusterMeta?.[index] || null;
    const { delay, duration } = computeTiming(index, meta, animStyle, speed);
    return `      <path d="${d}" fill-rule="evenodd" class="sig-p" style="animation-delay:${delay.toFixed(3)}s;animation-duration:${(duration * 0.4).toFixed(3)}s;"/>`;
  }).join('\n');

  const innerGroup = svgTransform && !isFill
    ? `    <g transform="${svgTransform}" fill="${DEFAULT_FILL}" stroke="none">\n${pathLines}\n    </g>`
    : `    <g fill="${DEFAULT_FILL}" stroke="none">\n${pathLines}\n    </g>`;

  return `<!-- Signature Animation — generated by Signature Animator -->
<div style="max-width:500px;">
  <svg viewBox="${vb}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;overflow:hidden;">
    <style>
      @keyframes sigFadeIn {
        from { opacity: 0; transform: scale(0.97); }
        to { opacity: 1; transform: scale(1); }
      }
      .sig-p {
        opacity: 0;
        animation-name: sigFadeIn;
        animation-fill-mode: forwards;
        animation-timing-function: ease-out;
      }
    </style>
${innerGroup}
  </svg>
</div>`;
}

export function generateStaticSVG({
  paths,
  isFill,
  viewBox,
  svgTransform,
  canvasWidth = DEFAULT_CANVAS_W,
  canvasHeight = DEFAULT_CANVAS_H,
}) {
  const vb = isFill ? `0 0 ${canvasWidth} ${canvasHeight}` : (viewBox || DEFAULT_VIEWBOX);

  const pathsMarkup = paths.map((d) => `    <path d="${d}" fill-rule="evenodd"/>`).join('\n');
  const innerGroup = svgTransform && !isFill
    ? `  <g transform="${svgTransform}" fill="${DEFAULT_FILL}" stroke="none">\n${pathsMarkup}\n  </g>`
    : `  <g fill="${DEFAULT_FILL}" stroke="none">\n${pathsMarkup}\n  </g>`;

  return `<svg viewBox="${vb}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;">\n${innerGroup}\n</svg>`;
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  downloadBlob(blob, filename);
}

export function downloadPNG(svgString, scale = 3, filename = 'signature.png') {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');
  const svgEl = doc.querySelector('svg');
  const vb = parseViewBox(svgEl?.getAttribute('viewBox') || DEFAULT_VIEWBOX);

  const canvas = document.createElement('canvas');
  canvas.width = Math.max(1, Math.round(vb.width * scale));
  canvas.height = Math.max(1, Math.round(vb.height * scale));
  const ctx = canvas.getContext('2d');

  if (!ctx) {
    throw new Error('Could not initialize PNG export canvas.');
  }

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  return new Promise((resolve, reject) => {
    const img = new Image();

    img.onload = () => {
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      URL.revokeObjectURL(url);

      canvas.toBlob((blob) => {
        if (!blob) {
          reject(new Error('Unable to encode PNG image.'));
          return;
        }
        downloadBlob(blob, filename);
        resolve();
      }, 'image/png');
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Unable to render SVG preview into PNG.'));
    };

    img.src = url;
  });
}
